# https://www.uiua.org/pad
I ← &sc                                                                                                      # get input from stdin
S ← {"0" "1" "2" "3" "4" "5" "6" "7" "8" "9"}                                                                # ruleset a
D ← {"0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "one" "two" "three" "four" "five" "six" "seven" "eight" "nine"} # ruleset b
∩(/+/+⊟×10∩(+×¯9>9.≡⊗⊙⍉/↧.≡(≡(⊗1⌕⊙⊔)¤⊔))⊃(⊙¤)(⊙¤∩≡⇌):⊜□≠@ .I)D S                                             # just do whatever
